name: CI for React App

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Lint JavaScript
        run: npx eslint "**/*.js"

      - name: Lint CSS
        run: npx stylelint "**/*.css"

      - name: Validate HTML
        run: java -jar vnu.jar --skip-non-html ./build

      - name: Run Lighthouse performance tests
        run: lighthouse https://example.com --output html --output json --output-path=./lighthouse-report.html

      - name: Upload Lighthouse report
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-report
          path: ./lighthouse-report.html