name: Run Lighthouse

on: push

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Install Lighthouse
      run: npm install -g lighthouse

    - name: Run Lighthouse and generate report
      run: lighthouse https://example.com --output html --output json --output-path=./lighthouse-report.html
      
    - name: Upload Lighthouse report
      uses: actions/upload-artifact@v2
      with:
        name: lighthouse-report
        path: ./lighthouse-report.html
